print("====================================")
print(" 🐍 PYTHON AI/BACKEND PROCESSOR 🐍 ")
print("====================================")

# Bash script ki banayi hui log file ko open karna
file_path = "health_log.txt"

try:
    with open(file_path, "r") as file:
        logs = file.readlines()
    
    print(f"📊 Total lines generated by Cron: {len(logs)}")
    print("🧠 Extracting latest RAM data...")
    
    # Niche se upar (reverse) padhna taaki sabse latest RAM dikhe
    for line in reversed(logs):
        if "Total RAM" in line:
            print(f"--> [PYTHON FOUND]: {line.strip()}")
            break # Ek baar latest mil gaya, toh loop rok do
            
except FileNotFoundError:
    print("❌ Error: Log file nahi mili. Kya bash script chali thi?")